---
title: Prospektive, multizentrische Beobachtungsstudie zur Bestimmung der Effizienz von Aktivkohlefiltern sowie der Wiedergewinnung von Sevofluran im OP
subtitle: Studienprotokoll
date: "`r format(Sys.Date(), '%d.%m.%Y')`"
author: "Dr. med. Sebastian Gibb"
cfg-acronym: VCT-OR-MC
cfg-version: 0.4
cfg-githash: "`r system('git rev-parse --short HEAD', intern = TRUE)`"
bibliography: bibliography.bib
output:
    bookdown::odt_document2:
        reference_odt: pandoc/reference/reference.odt
---

```{r helper_functions, include = FALSE}
.eval_meta <- function(x)eval(parse(text = gsub("(^`r\\s+)|(`$)", "", x)))
```

# Prüfplan-Synopsis

------------------------        --------------------------------------------------
**Bezeichnung der Studie**      Prospektive, multizentrische Beobachtungsstudie
                                zur Bestimmung der Effizienz von Aktivkohlefiltern
                                sowie der Wiedergewinnung von Sevofluran im OP.

**Studiendesign**               Prospektive, multizentrische Beobachtungsstudie

**Ziel der Studie**             Bestimmung der Effizienz von Aktivkohlefiltern
                                sowie der Wiedergewinnung von Sevofluran im OP.

**Studienzeitraum**             ab 01.06.2024 ca. 10 - 20 Wochen

**Version**                     `r paste(rmarkdown::metadata[["cfg-version"]], .eval_meta(rmarkdown::metadata[["cfg-githash"]]), sep = "_")`

**Datum**                       `r .eval_meta(rmarkdown::metadata$date)`
----------------------------------------------------------------------------------

# Verantwortlichkeiten und Kooperationen

## Studienleitung

Dr. med. Sebastian Gibb

E-Mail: sebastian.gibb\@med.uni-greifswald.de\
Telefon: 03834 865801\
Fax: 03834 865802\
\
Klinik für Anästhesie, Intensiv-, Notfall- und Schmerzmedizin\
Universitätsmedizin Greifswald\
Ferdinand-Sauerbruch-Straße\
\
17475 Greifswald - Deutschland

und

Dr. med. Stephanie Snyder-Ramos

E-Mail: stephanie.snyder-ramos\@stadtmission-hd.de\
Telefon: 06221 483364\
\
Abteilung für Anästhesie und Intensivmedizin\
Krankenhaus Salem der Evang. Stadtmission Heidelberg gGmbH\
Zeppelinstraße 11 - 33\
\
69121 Heidelberg - Deutschland

## Ansprechpartner und Zentren

- Dr. med. Stephan Knigge und Nadin Möller, Klinik für Anästhesiologie, Universitätsmedizin Greifswald, Deutschland
- Dr. med. Christian Lisson, Abteilung für Anästhesie und Intensivmedizin, Krankenhaus Salem der Evang. Stadtmission Heidelberg gGmbH, Deutschland
- Dr. med. Rüdiger Hacker, Abteilung für Anästhesie, Intensiv- und Schmerztherapie, Herz-Jesu-Krankenhaus Fulda gGmbH, Deutschland
- Dr. med. Ernst Trampitsch, Abteilung für Anästhesie und Intensivmedizin, Landeskrankenhaus Villach, Österreich
- Einschluss weiterer Zentren geplant

# Wissenschaftlicher Hintergrund

Die anthropogene Klimakatastrophe ist eine große Bedrohung für die globale Gesundheit [@Daalen2022].
Das Gesundheitssystem verursacht selbst ca. 5-10 \% der Treibhausgasemissionen [@Hu2021; @Hunfeld2022].
Ein Großteil dieser Emission hat die Anästhesie und Intensivmedizin zu verantworten [@Hu2021].

Bedeutsam sind dabei vor allem die inhalativen Anästhetika, die alle Fluor(chlor)kohlenwasserstoffe (F(C)KW) sind.

Mit CONTRAfluran bietet die Firma ZeoSys Medical GmbH einen Aktivkohlefilter an, der die Anästhesiegase, die bisher über das Anästhesiegasfortleitungsystem (AGFS) in die Umwelt abgegeben werden, auffängt.

Hinterberg et al. haben die Effektivität von CONTRAfluran im OP während der Nutzung von Desfluran untersucht und konnten nur 25% wiedergewinnen [@Hinterberg2022].
Aufgrund des höheren Blut-/Gas-Verteilungskoeffizienten und der höheren Metabolisierungsrate ist für Sevofluran bei längeren Narkosen eine niedrigere Effizienz zu erwarten.
Hingegen konnten Ghandi und Baxter mit einem anderen Aktivkohlefiltersystem (SID-Can, SageTech, UK), das im Gegensatz zum CONTRAfluran ein AGFS erfordert, knapp 50% des Sevoflurans wiedergewinnen [@Gandhi2023].

Die Effizienz der Wiedergewinnung ist in Simulationen vom Frischgasfluss und von der Narkosedauer abhängig [@Dexter2023].
In der noch laufenden Studie "VCT-OR: Prospektive Beobachtungsstudie zur Bestimmung der Effizienz von Aktivkohlefiltern sowie der Wiedergewinnung von Sevofluran im OP" (BB 102/23, 08.08.2023) haben wir an zwei Narkosegeräten vorläufige Auffangraten anhand von Gewichtzunahmen von ca. 40 und 75% ermittelt [@vctordata].
Die unterschiedlichen Narkosen, die an beiden Geräten durchgeführt werden, unterstützen die Hypothese der Simulationen.

Der Wirkungsgrad von CONTRAfluran für Sevofluran, dem klimafreundlichsten (trotz 140 CO~2~-Äquivalenten [@Nielsen2024]) inhalativen Anästhetikum, sowie dessen Abhängigkeit vom Frischgasfluss und der Narkosedauer ist von entscheidender Bedeutung für die Beurteilung dieser Methode.

# Fragestellung / Arbeitshypothese

Welcher Anteil an Sevofluran zur inhalativen Anästhesie kann mittels des Aktivkohlefilters CONTRAfluran im OP wiedergewonnen werden?

# Studientyp / Studiendesign

Multizentrische, prospektive Beobachtungsstudie.

# Zielkriterien

## Primäres Zielkriterium

- Anteil an durch den Aktivkohlefilter gefilterten und wiedergewonnenem Sevofluran.

## Sekundäres Zielkriterium

- Abhängigkeit der Wiedergewinnungsrate von der Narkosedauer.
- Abhängigkeit der Wiedergewinnungsrate vom Frischgasfluss.

# Methoden der Datenerhebung

Folgende zur Auswertung benötigten Daten werden erfasst:

- Gesamtanzahl verwendeter Sevofluranflaschen je OP und Zentrum.
- Gesamtanzahl und Laufzeit verwendeter CONTRAfluran-Filter je OP und Zentrum.
- Medianer Frischgasfluss je OP und Zentrum.
- Mediane Narkosedauer je OP und Zentrum.
- Rückgewonnene Menge an Sevofluran durch die Firma ZeoSys Medical GmbH.

Es findet keine Erhebung personenbezogener Daten statt.

# Patienten/Probandencharakteristika

Die Entscheidung zur inhalativen Anästhesie obliegt dem betreuenden Anästhesisten/der betreuenden Anästhesistin.
Es werden keinerlei Patientendaten erhoben.

## Patienten/Probandenpopulation

Nicht zutreffend.

## Einschlusskriterien

keine

## Ausschlusskriterien

keine

# Kompensation der Aufwendungen

keine

# Versuchsablauf

## Ablauf in den teilnehmenden Studienzentren

Jedes teilnehmende Zentrum stellt für jeden teilnehmenden OP 10 Flaschen
Sevofluran zu Verfügung.
Diese Flaschen werden mit den IDs für das Zentrum, den OP und der jeweiligen
Flaschennummer markiert.

Zum Studienstart wird vor der ersten Narkose des Tages für jeden teilnehmenden
OP ein neuer CONTRAfluran-Filter installiert und ebenfalls
mit der ID für das Zentrum, den OP und einer laufenden Filter ID markiert.

Zusätzlich wird der Sevofluranvapor aus einer Sevofluranflasche, die nicht zu
dem Set der Studienflaschen gehört, maximal befüllt.

Das Set der markierten Sevofluranflaschen verbleibt in dem OP-Saal.

In jeder Narkose wird folgender Dokumentationsbogen ausgefüllt bzw. fortgeführt.

+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **VCT-OR-MC**, Studienleitung: Sebastian Gibb, Telefon: 03834 86-5801, E-Mail: sebastian.gibb\@med.uni-greifswald.de, Fax: 03834 86-5802                                           |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| Studienzentrum: VCT-OR-MC-HGW | OP: Saal 1                                                                                                                                         |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
Table: Dokumentationsbogen mit beispielhaften Einträgen.

+-----------------+-------------------------+------------------------+------------+--------+-------+---------------------+-----------------------+-----------------+
| CONTRAfluran ID | CONTRAfluran Filter Nr. | Sevofluran Flasche Nr. | Datum      | Beginn | Ende  | Inhalative Narkose? | Mittlerer FGF (l/min) | Kommentar       |
+=================+=========================+========================+============+========+=======+=====================+=======================+=================+
| CH0100012080    | 1                       |  1                     | 01.06.2024 | 08:00  | 09:30 | ja                  | 0.5                   |                 |
+-----------------+-------------------------+------------------------+------------+--------+-------+---------------------+-----------------------+-----------------+
| CH0100012080    | 1                       |  1                     | 01.06.2024 | 9:30   | 11:00 | nein                | 0.5                   |                 |
+-----------------+-------------------------+------------------------+------------+--------+-------+---------------------+-----------------------+-----------------+
| ...             | ...                     |  ...                   | ...        | ...    | ...   | ...                 | ...                   |                 |
+-----------------+-------------------------+------------------------+------------+--------+-------+---------------------+-----------------------+-----------------+
| CH0100012080    | 1                       |  2                     | 10.06.2024 | 08:00  | 10:25 | ja                  | 0.5                   | Flaschenwechsel |
+-----------------+-------------------------+------------------------+------------+--------+-------+---------------------+-----------------------+-----------------+

Der Vapor wird bis zum Verbrauch der letzten Studienflasche ausschließlich mit
diesen Flaschen befüllt.
Die Studie endet für den jeweiligen OP mit dem Auffüllen des Vapors mit der
letzten markierten Sevofluranflasche.
Zu diesem Zeitpunkt wird auch der installierte CONTRAfluran-Filter
**unabhängig** von seinem Füllstand dekonnektiert.

Spätestens zum Studienende werden die Dokumentationsbögen postalisch oder als
Scan per E-Mail an die Studienleitung geschickt.
Die Sevofluranflaschen werden entsprechend der Richtlinien des teilnehmenden
Zentrums entsorgt.
Die CONTRAfluran-Filter werden wie in dem jeweiligen Zentrum üblich
an ZeoSys geschickt, dort bis zum Abschluss der Studien in allen Zentren
gesammelt und dann gemeinsam der Wiedergewinnung zugeführt.

Während des Studienzeitraums ist in dem OP-Saal bzw. an den
Studien-CONTRAfluran-Filtern kein Mischbetrieb verschiedener volatiler
Anästhetika erlaubt. Wenn sich die\*der Anästhesist\*in für eine volatile
Anästhesie entscheidet, ist ausschließlich Sevofluran zu verwenden.

Die Verwendung von anderen volatilen Anästhetika, wie z.B. Desfluran oder
Isofluran oder das Auffüllen des Vapors mit einer Sevofluranflasche, die nicht
Teil der Studie ist, führt zum Ausschluss des jeweiligen CONTRAfluran-Filters.

## Ablauf und Aufgaben der Studienleitung - Universitätsmedizin Greifswald

Zum Studieneinschluss erhält jedes Zentrum die Vorlage für den
Dokumentationsbogen, Aufkleber zur eindeutigen Markierung der Sevofluranflaschen
und der CONTRAfluran-Filter.

Nach Abschluss der Datenerhebung und Erhalt der Dokumentationsbögen der
jeweligen Zentren wird für jeden CONTRAfluran-Filter der mittlere
Frischgasfluss bzw. mittlere Narkosedauer als Median
über alle für diesen Filter dokumentierten Frischgasflüsse bzw. Narkosedauern
bei inhalativen Narkose gebildet.
Die Menge des verbrauchten Sevoflurans je CONTRAfluran-Filter
wird anhand der Laufzeit (Summe der Dauer inhalativer Narkosen) des jeweiligen
Filters im Verhältnis zur Gesamtlaufzeit (Summe aller
Filterlaufzeiten) aller Filter ermittelt
(10 * 250 ml * (Laufzeit Filter/Gesamtaufzeit)).

Anhand des medianen Frischgasflusses und der medianen Narkosedauer werden die CONTRAfluran-Filter in folgende vier Untergruppen aufgeteilt:

- MINFLOW-SHORT: mittlerer Frischgasfluss <= 0.5 l/min und durchschnittliche Narkosedauer <= 1 Stunde
- MINFLOW-LONG: mittlerer Frischgasfluss <= 0.5 l/min und durchschnittliche Narkosedauer > 1 Stunde
- LOWFLOW-SHORT: mittlerer Frischgasfluss > 0.5 l/min und durchschnittliche Narkosedauer <= 1 Stunde
- LOWFLOW-LONG: mittlerer Frischgasfluss > 0.5 l/min und durchschnittliche Narkosedauer > 1 Stunde

Für einen Wiedergewinnungsprozess werden mindestens 20 CONTRAfluran-Filter benötigt.
Sollte diese Mindestanzahl für eine Gruppe nicht zu Stande kommen, werden die
folgenden zwei Untergruppen gebildet:

- SHORT: durchschnittliche Narkosedauer <= 1 Stunden
- LONG: durchschnittliche Narkosedauer > 1 Stunden

Wir behalten uns vor, den Grenzwert für die Narkosedauer von 1 Stunde zu
Gunsten von ähnlichen Gruppengrößen anzupassen.
Eine Anpassung des Grenzwertes für den Frischgasfluss ist nicht vorgesehen.

Die Zuordnung der CONTRAfluran-Filter zu den jeweiligen Gruppen durch die
Studienleitung wird an ZeoSys geschickt.
Dort wird für jede Gruppe ein bzw. mehrere separate Wiedergewinnungsprozesse durchgeführt und die
jeweilig zurückgewonnene Menge an Sevofluran an die Studienleitung übermittelt.

Die Untergruppen der CONTRAfluran-Filter werden durch deskriptive Statistik
analysiert.
Die wiedergewonnenem Menge Sevofluran wird mit der eingesetzten Menge
je Gruppe verglichen.

Eine induktive Statistik/ein Hypothesentest kann bei vier Gruppen mit je nur
einer Beobachtung (Menge an wiedergewonnenem Sevofluran) nicht durchgeführt werden.

## Limitationen

Um möglichst geringe Anforderungen an die Zentren zu stellen, um vielen Zentren
einzuschließen, und den Ablauf im OP nicht zu beeinflussen, wählen wir einen
pragmatischen Ansatz, der jedoch einige Schwächen und damit Ungenauigkeiten
aufweist.

### Limitationen bei Bestimmung des Sevofluranverbrauch

Die Restfüllung des Sevofluranvapors im Studien-OP kann vor Studienbeginn nicht eindeutig zu ermittelt werden,
somit ist maximale Füllung des Vapors unabdingbar um gleiche Ausgangsvoraussetzungen zu schaffen.
Jedoch führt dies dazu, dass je nach Nachfüllstrategie beim Auffüllen mit der
letzten Studien-Sevofluranflasche die Vaporfüllung unvollständig sein wird und
aufgrund der initialen Füllung mehr als die 10 Flaschen Sevofluran verbraucht
worden sein kann.
Die beiden häufig eingesetzten Vaporen 2000 und 3000 von Dräger haben ein
Nachfüllvolumen von 260 ml (eine Sevoflasche 250 ml).
Die größte zu erwartende Abweichung wäre somit eine Unterschätzung des
Verbrauches um 10%.

Eine Alternative wäre den Vapor vor Studienbeginn komplett zur leeren, dies ist
jedoch sehr kompliziert und erfordert in der Regel die Unterstützung der
Medizintechnik.

Der Goldstand zur Ermittlung des Verbrauchs von volatilen Anästhetika ist das
Wiegen des Vapors.
Das erfordert jedoch sehr teuere Spezialwaagen, da der Vapor 9 kg wiegt, aber
Veränderungen im Miligrammbereich gemessen werden müssen.
Solche Waagen sind an keinem Zentrum verfügbar.
Alternativ könnte man, wie in der Vorläuferstudie VCT-OR, die Sevofluranflaschen
vor und nach jedem Nachfüllvorgang wiegen.
Dadurch würde der Studienablauf an vielen Zentren deutlich komplizierter werden und auch,
wenn solche Meßbereiche durch einfachere Waagen erfasst werden können, sind
diese nicht an jedem Zentrum vorhanden.

### Limitationen bei der Wiedergewinnung von Sevofluran

Der letzte CONTRAfluran-Filter je Zentrum und OP wird nicht vollständig beladen sein.
Das senkt die Effizienz des Wiedergewinnungsprozesses.

Methodisch bedingt sind 20 CONTRAfluran-Filter für einen Wiedergewinnungsprozess
notwendig.
Die Aufteilung in vier Untergruppen kann zu einer "Unterfüllung" führen, wenn
die Gruppengröße weit von einem Vielfachen von 20 abweicht und die
Effizenz weiter senken.

### Limitation beim Erfassen des Frischgasflusses

Der Frischgasfluss ist bei jeder Narkose eine dynamische Größe.
Üblicherweise wird mit einem höheren Frischgasfluss begonnen, um Sevofluran
"einzuwaschen".
Wenn die Patient\*innen und das Kreisteil aufgesättigt sind, kann der
Frischgasfluss reduziert werden.
Hier können Leckagen, operationsbedingte Manipulationen am
Thorax/Zwerchfell/Atemweg zur temporären Erhöhung des Frischgasflusses führen.
Nichtsdestotrotz gibt es in der Regel ein Steady-State in dem wir den
Frischgasfluss erfassen wollen und somit als Surrogatparameter für die Effizienz
der Narkoseführung nehmen.

# Patienten/Probandensicherheit

## Nebenwirkungen

Da es sich um eine reine Beobachtungsstudie ohne Intervention am Patienten
handelt, sind keine studienbedingten Nebenwirkungen zu erwarten.

## Risiken der Versuchsdurchführung

keine

## Abbruchkriterien

keine

# Gesetze / Verordnungen, die bei dem Vorhaben zu beachten sind

- Deklaration von Helsinki (in der aktuellen Fassung)
- Berufsordnung der Ärztinnen und Ärzte in Mecklenburg-Vorpommern (unter besonderer Berücksichtigung des §15 bzw. vergleichbare Abschnitte in dem jeweiligen Bundesland des teilnehmenden Zentrums).

# Überlegungen zum Abschluss einer Probandenversicherung/Wegeunfallversicherung

Da es sich um eine reine Beobachtungsstudie ohne Intervention am Patienten
handelt, entfällt die Notwendigkeit einer zusätzlichen Probandenversicherung.

# Statistische Planung

Da es sich um eine reine Beobachtungsstudie ohne Intervention am Patienten
ist keine Fallzahlschätzung notwendig.

Es ist eine rein deskriptive Datenanalyse geplant.

# Datenmanagement / Biologische Marker

Die Daten werden tabellarisch in einem Tabellenkalkulationsprogramm (vgl. MS Excel) erfasst und
auf dem Forschungslaufwerk der Klinik für Anästhesiologie passwortgeschützt gespeichert.
Eine Weitergabe an Dritte ist nicht vorgesehen.
Die Ergebnisse zur Effizienz der Filter sollen veröffentlicht werden.
Patientendaten werden nicht erhoben und nicht veröffentlicht.

# Patienten/Probanden-Information und Einwilligungserklärung mit Datenschutzerklärung

Die Studie soll die Effektivität der Aktivkohlefilter und der Wiedergewinnung von Sevofluran untersuchen.
Es erfolgt keine Erhebung personenbezogener Daten.
Eine Einwilligung der Patienten ist nicht notwendig.

# Unterschrift und Erklärung

Der Projektleiter bestätigt mit der Unterschrift,

- dass auch bei einer positiven Beurteilung des Vorhabens durch die Ethikkommission
an der Universitätsmedizin Greifswald die ärztliche und juristische Verantwortung
uneingeschränkt bei dem/der Projektleiter/in und seinen Mitarbeiter/innen
verbleibt.
- die Richtigkeit und Vollständigkeit dieses Antrages.


Greifswald, `r .eval_meta(rmarkdown::metadata$date)`

`r rmarkdown::metadata$author`

# Referenzen
