---
title: Studienfortschritt
---

- [Studienübersicht](index.html)
- [Übersicht Datenvalidierung](validate.html)

Letzte Aktualisierung: `r format(Sys.time())`

# Gesamtübersicht

```{r import, echo = FALSE, messages = FALSE}
suppressPackageStartupMessages(library("lubridate"))
library("minair")

setting <- read.csv(find_git_root_file("raw-data", "setting.csv"))

crf <- do.call(
    rbind,
    lapply(
        list.files(
            find_git_root_file("raw-data", "crfs"),
            pattern = "*\\.csv",
            full.names = TRUE
            ),
        function(x)read.csv(
            x, comment.char = "#", na.strings = c("NA", ""), tryLogical = FALSE
        )
    )
)

ncenters <- length(unique(crf$center.id))
nors <- nrow(unique(crf[, c("center.id", "or.id")]))
nagcs <- length(unique(crf$agc.id))
nbottles <- nrow(unique(crf[, c("center.id", "or.id", "bottle.number")]))
ncases <- nrow(crf)

knitr::kable(
    c(
        `Aktive Zentren` = ncenters,
        `Teilnehmende OP-Säle` = nors,
        `CONTRAfluran-Filter` = nagcs,
        `Begonnene Sevofluranflaschen` = nbottles,
        `Anzahl Anästhesien` = ncases
    ),
    col.names = c("N"),
    caption =
        paste0("Gesamtübersicht. ")
)
```

# Übersicht über den Fortschritt der teilnehmenden OPs

```{r progess, results = "asis", echo = FALSE}
or <- sprintf("%02.f-%02.f", setting$center.id, setting$or.id)
crf$or <- sprintf("%02.f-%02.f", crf$center.id, crf$or.id)
uor <- sort(unique(crf[["or"]]))

progress <- vector(mode = "list", length = length(or))
names(progress) <- or
progress[or] <- 0

progress[uor] <- tapply(
    crf$bottle.number, crf[["or"]],
    \(x)max(c(0, (ifelse(x == 10, 10.5, x) - 0.5) * 10), na.rm = TRUE)
)

for (o in or) {
    cat(
        '<div class = "row">',
        '<div class = "col-md-2">',
        o,
        '</div>',
        '<div class = "col-md-10">',
        '<div class="progress">',
        if (progress[[o]] > 99) {
            '<div class="progress-bar progress-bar-success"'
        } else {
            '<div class="progress-bar"'
        },
        ' role="progressbar" style="width: ', progress[[o]], '%;" aria-valuenow="', progress[[o]], '" aria-valuemin="0" aria-valuemax="100"></div>',
        '</div>',
        '</div>',
        '</div>',
        sep = ""
    )
}
```

# Übersicht über CONTRAfluran-Filter

```{r agc-characteristics, echo = FALSE}
#' @param x `data.frame`, crf, for one AGC
agcchar <- function(x) {
    d <- as.double(ymd_hms(x$end) - ymd_hms(x$start), units = "mins")
    a <- ifelse(x$airway == "L", 0, 1)

    f <- expand.grid(
        airway = c("L", "T"),
        laparoscopic = 0:1,
        balanced.anaesthesia = 0:1
    )
    dur <- apply(
        f,
        MARGIN = 1,
        function(ff)sum(
            d[
                x$airway == ff[[1L]] & x$laparoscopic == ff[[2L]] &
                x$balanced.anaesthesia == ff[[3L]]
            ],
            na.rm = TRUE
        )
    )
    flow <- apply(
        f,
        MARGIN = 1,
        function(ff)median(
            x$flow[
                x$airway == ff[[1L]] & x$laparoscopic == ff[[2L]] &
                x$balanced.anaesthesia == ff[[3L]]
            ],
            na.rm = TRUE
        )
    )
    nf <- paste(
        ifelse(f[["airway"]] == "L", "lama", "tube"),
        ifelse(f[["laparoscopic"]], "lap", "nonlap"),
        ifelse(f[["balanced.anaesthesia"]], "inha", "tiva"),
        sep = "."
    )

    names(dur) <- paste("sum", "dura", nf, sep = ".")
    names(flow) <- paste("med", "flow", nf, sep = ".")

    c(
        median.duration = median(d, na.rm = TRUE),
        mean.flow = weighted.mean(x$flow, d, na.rm = TRUE),
        mean.balanced.anaesthesia = weighted.mean(
            x$balanced.anaesthesia, d, na.rm = TRUE
        ),
        mean.airway = weighted.mean(a, d, na.rm = TRUE),
        mean.laparoscopic = weighted.mean(x$laparoscopic, d, na.rm = TRUE),
        dur,
        flow,
        ncases = nrow(x)
    )
}

agcs <- as.data.frame(
    t(do.call(cbind, tapply(crf, crf$agc.id, agcchar)))
)

agcs$weight <- 400

agcs[is.na(agcs)] <- 0

mdl <- lm(weight ~ 0 +
    sum.dura.lama.nonlap.tiva +
    sum.dura.tube.nonlap.tiva +
    sum.dura.tube.lap.tiva +
    sum.dura.lama.nonlap.inha +
    sum.dura.tube.nonlap.inha +
    sum.dura.tube.lap.inha +
    med.flow.lama.nonlap.tiva +
    med.flow.tube.nonlap.tiva +
    med.flow.tube.lap.tiva +
    med.flow.lama.nonlap.inha +
    med.flow.tube.nonlap.inha +
    med.flow.tube.lap.inha,
    data = agcs
)

knitr::kable(
    agcs[c(
        "median.duration", "mean.flow", "mean.balanced.anaesthesia",
        "mean.airway", "mean.laparoscopic", "ncases"
    )],
    col.names = c(
        "Mediane Dauer", "Mittlerer Frischgasfluss",
        "Anteil balanc. Anästhesien", "Anteil Tubus",
        "Anteil Laparoskopien", "Anzahl Anästhesien"
    ),
    digits = 2
)

knitr::kable(coef(mdl))
```

```{r plot-agc, echo = FALSE, fig.cap = "Mediane Narkosedauer ggü. mittlerem Frischgasfluss je CONTRAfluran-Filter"}
old.par <- par(no.readonly = TRUE)
on.exit(par(old.par))

plot(NA,
    xlim = c(0, max(agcs$median.duration, na.rm = TRUE)),
    ylim = c(0, max(agcs$mean.flow, na.rm = TRUE)),
    axes = FALSE, xlab = "", ylab = ""
)
points(
    agcs$median.duration, agcs$mean.flow,
    pch = ifelse(agcs$mean.airway > 0.5, 16, 17),
    col = ifelse(agcs$mean.laparoscopic > 0.5, "#21908CF0", "#440154F0")
)
title(main = "Mediane Anästhesiedauer vs mittlerem Frischgasfluss je CONTRAfluran-Filter", col.main = "#808080", adj = 0L, cex.main = 0.9)
title(xlab = "MEDIANE ANÄSTHESIEDAUER [min]", adj = 0L, col.lab = "#808080")
title(ylab = "MITTLERER FRISCHGASFLUSS [l/min]", adj = 1L, col.lab = "#808080")
axis(1L, col = "#808080", col.axis = "#808080", lwd.ticks = 0)
axis(2L, col = "#808080", col.axis = "#808080", lwd.ticks = 0, las = 2)
legend(
    "topright",
    legend = c(
        "nicht-laparoskopisch", "laparoskopisch",
        "Tubus", "Larynxmaske"
    ),
    col = c(
        "#440154F0", "#21908CF0",
        "#808080", "#808080"
    ),
    pch = c(
        15, 15,
        16, 17
    ),
    bty = "n"
)
```
